// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppGetConfig(arg1:string):Promise<any>;

export function AppSetConfig(arg1:string,arg2:any):Promise<boolean>;

export function AppSetOverride(arg1:string,arg2:any):Promise<boolean>;

export function CloseWindow():Promise<void>;
