// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GreetName(arg1) {
  return window['go']['service']['service']['GreetName'](arg1);
}
