// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppGetConfig(arg1) {
  return window['go']['service']['service']['AppGetConfig'](arg1);
}

export function AppGetConfiguration() {
  return window['go']['service']['service']['AppGetConfiguration']();
}

export function AppSetConfig(arg1, arg2) {
  return window['go']['service']['service']['AppSetConfig'](arg1, arg2);
}

export function CloseWindow() {
  return window['go']['service']['service']['CloseWindow']();
}

export function GreetName(arg1) {
  return window['go']['service']['service']['GreetName'](arg1);
}
